# Generated by Django 4.2.4 on 2023-12-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('time', models.TimeField(default='10:00', verbose_name='Время напоминания')),
                ('action', models.CharField(blank=True, max_length=150, null=True, verbose_name='Действие')),
                ('frequency', models.SmallIntegerField(default=1, verbose_name='Периодичность напоминания в днях')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.TimeField(default='00:01', verbose_name='Время выполнения')),
                ('last_reminder_date', models.DateField(default=datetime.date(2023, 12, 17), verbose_name='Дата последнего напоминания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Видна всем')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Хорошая привычка',
                'verbose_name_plural': 'Хорошие привычки',
            },
        ),
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('time', models.TimeField(default='10:00')),
                ('action', models.CharField(blank=True, max_length=150, null=True, verbose_name='Действие')),
                ('frequency', models.SmallIntegerField(default=1, verbose_name='Периодичность напоминания в днях')),
                ('execution_time', models.TimeField(default='00:01', verbose_name='Время выполнения')),
                ('last_reminder_date', models.DateField(default=datetime.date(2023, 12, 17), verbose_name='Дата последнего напоминания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Видна всем')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
    ]
